name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like to implement
      placeholder: |
        Add support for batch testing multiple files at once
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Other alternatives could be..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: "Add any other context or screenshots here"

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this feature belong to?
      options:
        - Test Script (icap_test.py)
        - ICAP Server (icap_server.py)
        - Docker / Deployment
        - Documentation
        - Performance
        - Other
    validations:
      required: true
