name: Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please describe your question in detail. Make sure to check the documentation first!

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What is your question about?
      options:
        - Installation
        - Usage
        - Configuration
        - ICAP Protocol
        - Docker
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "How do I configure the ICAP server to use a custom ClamAV instance?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Any error messages?

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      options:
        - 1.0.9 (latest)
        - 1.0.8
        - 1.0.7
        - Other
